### ISSUE TITLE
build problems (ubuntu 18.04)

### ISSUE THREAD

**Issue by ohenley** [stcarrez/atlas#1]
Hi Stephane,

I tried to build Atlas an I run into many problems. I first build AWA because it brings all the repos necessary for Atlas and I though make install would set me up all the dependencies, system wide, for building Atlas. ./configure works, make works, make install seems to work. (as I find your stuff, eg /usr/local/lib/util.static/, /usr/local/lib/ado.static etc )

1. when I try to ./configure Atlas, it does not find Ada-Util (first one to break). The output says it looked in /usr/local/lib/gnat/lib as is my new ADA_PROJECT_PATH variable set, tampered with. There is no folder /usr/local/lib/gnat/lib on my machine...?

2. Therefore I decide to move the folder atlas inside ada-awa. Now ./configure of Atlas works but make breaks:
a) atlas.gpr, with "config" conflicts with/probably config.gpr from other submodule included just after.
I fixed it by renaming the atlas config.gpr by config_atlas.gpr everywhere needed.
b) Also in the generated atlas.gpr, the pattern with "../awa/awa_mail"; is not good. I think it should read "../awa/plugins/awa-mail/awa_mail.gpr";

Now it goes on to build the atlas-server binary.

When I execute bin/atlas-server and ...
INFO : Connect your browser to http://localhost:8080/atlas//index.html

This is the output I get: 
DEBUG: Finding route for //index.html
DEBUG: Finding route for /setup/install.html
INFO : GET /setup/install.html
INFO : Dispatch /setup/install.html
DEBUG: Inject route parameters from /setup/install.html
DEBUG: Find facelet /setup/install.xhtml
WARN : Cannot read '/setup/install.xhtml': file does not exist
WARN : Page not found: /setup/install.html
DEBUG: Finding route for /setup/install.html
INFO : GET /setup/install.html
INFO : Dispatch /setup/install.html
DEBUG: Inject route parameters from /setup/install.html
DEBUG: Find facelet /setup/install.xhtml
WARN : Cannot read '/setup/install.xhtml': file does not exist
WARN : Page not found: /setup/install.html

From there I check more closely and found that, probably, the content of the web folder of the awa-setup should be reachable by atlas-server. I merged the content of awa-setup/web to atlas/web. Now there is a page that shows up but it is broken in every way possible. The browser console shows stuff like

GET http://localhost:8080/atlas/css/grids/reset.css 404 (Not Found) (locate cmd tells me it comes from ada-asf or ada-security
GET http://localhost:8080/atlas/css/users.css 404 (Not Found)
etc etc

I did the merge of all web folders to atlas/web by hand but it is tedious and still, there is many jquery *.js (mouse, core, etc) stuff that do not follow along properly, wrong placement. At this point I let go.
   
Let me know if I tried building the wrong way and/or how should I deploy all the relevant stuff to atlas/web.

Thx

**Comment by stcarrez** [comment]
Hi!

I think your ADA_PROJECT_PATH is not correct.
It should contain **/usr/local/share/gpr**.
You should find the `util.gpr`, `awa.gpr` and other GNAT project files there.

Building Atlas by moving the sources to AWA is not supported.
All the paths to the different GNAT projects have to be setup and there are many AWA plugins.
I've never done it.

The last issue you are facing, is fixed by running in the Atlas directory the command:

```
make generate
```

or you can also run the command
```
dynamo info
```
When you run this **dynamo generate** or **dynamo info** commands, it updates the
**atlas.properties** file to setup the dynamo_search_dirs variable. That variable contains
the path where the html, css, javascript, and other files are installed in your system.
(it should be in /usr/local/share/dynamo).

Doing the web merge by hand is really not the good solution. It's painful.
Basically, the dynamo tool looks at the GNAT project as well as the dynamo.xml file and
it builds that search path. Basically, each AWA module that you use will appear
in the search path.  That is you should see something like:

```
dynamo_search_dirs=/usr/local/share/dynamo/awa_flotcharts;/usr/local/share/dynamo/awa_markedit;.;/usr/local/share/dynamo/awa_setup;/usr/local/share/dynamo/awa_wikis;/usr/local/share/dynamo/awa_votes;/usr/local/share/dynamo/awa_questions;/usr/local/share/dynamo/awa_blogs;/usr/local/share/dynamo/awa_counters;/usr/local/share/dynamo/awa_images;/usr/local/share/dynamo/awa_jobs;/usr/local/share/dynamo/awa_storages;/usr/local/share/dynamo/awa_comments;/usr/local/share/dynamo/awa_tags;/usr/local/share/dynamo/awa_mail;/usr/local/share/dynamo/awa_workspaces;/usr/local/share/dynamo/awa;/usr/local/share/dynamo/ado;/usr/local/share/dynamo/asf
```

Sorry for these problems, I'll try to improve the documentation to clarify this.

By the way, I've started a programmer's guide that you may have a look at
http://ada-awa.readthedocs.io/en/latest/

I still have a lot of documentation to write but you may find it useful (I hope!)...

Stephane

**Comment by ohenley** [comment]
Ah great! I will give a shot to all this.

Thank you for the quick answer!

note: I used the docker container and it works great.

**Comment by ohenley** [comment]
Hi Stephane,

I restarted from scratch and I still miss information/knowledge to build a
test app. followed instructions up to
http://ada-awa.readthedocs.io/en/latest/Tutorial/

Install ada-awa. everything is fine.

then:

dynamo -o ohtest create-project -l apache ohtest email@domain.com1

then ./configure:

breaks for ada-servlet. The gpr file/files have not been placed in
/usr/local/share/gpr. If I go in ada-servlet and do make install, it errors
on uninstall. I remove the uninstall from the install in the Makefile and
it went further.

Once I have the ohtest-server built, running it, I get into:

ERROR: setup.xml: File 'setup.xml' does not exist.
INFO : Get driver mysql
INFO : Register driver sqlite
INFO : Loading driver libada_ado_mysql.so
ERROR: Driver for mysql was not found: libada_ado_mysql.so: cannot open
shared object file: No such file or directory
ERROR: No driver found for connection URI:
mysql://localhost:3306/ohtest?user=ohtest
INFO : Clearing bundle cache
INFO : Clearing facelet cache
ERROR: Exception in server: ADO.DRIVERS.CONNECTION_ERROR: Driver 'mysql'
not found

My Mysql server is running, I created a databse named ohtest and a user
ohtest.

What should go inside setup.xml?
Why does it get driver mysql but register sqlite?
Do you know what I am missing?

Thank you,

Olivier

**Comment by ohenley** [comment]
I did some progress.

1) ADA_PROJECT_PATH had ; separator between paths ... it looks it works in a different behaviour. Everything looks fine since I use : separator.

2) I needed apt-get install libmysqlclient-dev

Now I get the wanted --> INFO : Connect your browser to http://localhost:8080/index.html
... but my browser receives a 404 error when I visit?

**Comment by stcarrez** [comment]
Great!

Each application has a name and is registered under a given root URI.
So, the correct URL to connect to your application is http://localhost:8080/ohtest/index.html

This name comes from the content of the `<app>.Applications.CONTEXT_PATH` string variable in the package specification.

**Comment by ohenley** [comment]
After doing dynamo info, I get to the db creation page. When my Mysql root user is properly created with a password, I get this:

Connecting to mysql://localhost:3306/?user=olivier&password=XXXXXXXX for database setup
ERROR: create-database.xml: File 'create-database.xml' does not exist.
ERROR: Query failed: ''
ERROR:   with error: 'Query was empty'
error: Query failed: Query was empty

Do I have to c&p /home/olivier/Ada/ada-awa/dynamo/config/db/create-database.xml to
the ohtest folder? I tried directly in ohtest, in config, in config/db ... it is not going through.

Any idea? Thx.

**Comment by stcarrez** [comment]
My fault!  I forgot to push one commit in dynamo repository to fix that issue.

https://github.com/stcarrez/dynamo/commit/e867612675a8695658f12676b1669aa68a67e576

Get the commit and re-build dynamo, then re-install AWA.

You don't need to copy anything else. The web setup application will launch dynamo and it is supposed
to do the job and find its configuration files where you installed dynamo.

I realize you may reach another problem, at least, I'm seeing something broken on my side.
When you launch `dynamo generate db`, it generates the Ada code (if necessary) but it also
generates MySQL and SQLite files for the database creation.  These files are locates in

db/mysql
db/sqlite

These directories should contain files such as

ohtest-mysql.sql
ohtest-sqlite.sql

These files are generated by Dynamo by merging the SQL files that every AWA module provides.
It depends on what modules you decide to use.

I think I broke the final SQL generation and maybe these files are not there.

**Comment by stcarrez** [comment]
I've opened an issue on Dynamo because I really broke something in December 2017.
The final SQL files are no longer generated.

https://github.com/stcarrez/dynamo/issues/1

**Comment by ohenley** [comment]
Super.

If you can, poke me when things are cleared, I'll give another try.

Thx.

**Comment by stcarrez** [comment]
Yes. I'm making good progress.
I'm also fixing several issues that are now reported by GNAT 2018.

**Comment by stcarrez** [comment]
Many improvements since 2018...

We can now also build AWA and Atlas by using Alire.
